export const fishies = [
    {
      info: "Bottomfish fishing operations, typically using weighted lines and baited hooks, do not have adverse impacts to the habitat.",
      region: "Pacific Islands",
      scientificName: "Pristipomoides filamentosus",
      illustrationPhoto: {
        src: "images/pink_snapper.png",
        alt: "Pink snapper",
        title: "Pink snapper",
      },
      Name: "Crimson Jobfish",
      index:1,
    },
    {
      info: "Area closures and gear restrictions protect habitats that are affected by some kinds of trawl gear.",
      region: "Greater Atlantic",
      scientificName: "Urophycis tenuis",
      illustrationPhoto: {
        src: "images/white_hake.jpg",
        alt: "Illustration of white hake. Credit: Jack Hornady.",
        title: "",
      },
      Name: "White Hake",
      index:2,
    },
    {
      info: "Area closures and gear restrictions protect habitat that are affected by some types of trawl gear.",
      region: "Greater Atlantic",
      scientificName: "Scomber colias",
      illustrationPhoto: {
        src: "images/atlantic_mackerel.png",
        alt: "Illustration of Atlantic chub mackerel",
        title: "Atlantic chub mackerel",
      },
      Name: "Atlantic Chub Mackerel",
      index:3,
    },
    {
      info: "Fishing gears used to harvest shortfin squid have minimal impacts on habitat.",
      region: "Greater Atlantic",
      scientificName: "Illex illecebrosus",
      illustrationPhoto: {
        src: "images/shortfin_squid.png",
        alt: "shortfin squid",
        title: "Shortfin Squid",
      },
      Name: "Shortfin Squid",
      index:4,
    },
    {
      info: "Fishing gears used to harvest American lobster have minimal impacts on habitat.",
      region: "Greater Atlantic",
      scientificName: "Homarus americanus",
      illustrationPhoto: {
        src: "images/american_lobster.png",
        alt: "American Lobster",
        title: "American Lobster",
      },
      Name: "American Lobster",
      index:5,
    },
    {
      info: "Most fishing gear used to harvest yellowtail rockfish rarely contacts the ocean floor and has minimal impacts on habitat. Area closures and gear restrictions protect sensitive rocky, cold-water coral and sponge habitats from bottom trawl gear.",
      region: "West Coast, Alaska",
      scientificName: "Sebastes flavidus",
      illustrationPhoto: {
        src: "images/yelloweye_rockfish.jpg",
        alt: "Yellowtail rockfish",
        title: "Yellowtail rockfish",
      },
      Name: "Yellowtail Rockfish",
      index:6,
    },
    {
      info: "Area closures and gear restrictions protect sensitive rocky, cold-water coral and sponge habitats from bottom trawl gear.",
      region: "West Coast, Alaska",
      scientificName: "Sebastes paucispinis",
      illustrationPhoto: {
        src: "images/bocaccio_rockfish.jpg",
        alt: "Illustration of a Bocaccio rockfish.",
        title: "Bocaccio rockfish.",
      },
      Name: "Bocaccio",
      index:7,
    },
    {
      info: null,
      region: "West Coast, Greater Atlantic, Alaska",
      scientificName: "Saccharina latissima",
      illustrationPhoto: {
        src: "images/sugar_kelp.jpg",
        alt: "",
        title: "",
      },
      Name: "Sugar Kelp",
      index:8,
    },
    {
      info: null,
      region: "West Coast",
      scientificName: "Anoplopoma fimbria",
      illustrationPhoto: {
        src: "images/sablefish.jpg",
        alt: "",
        title: "",
      },
      Name: "Sablefish",
      index:9,
    },
    {
      region: "Greater Atlantic",
      scientificName: "Hippoglossus hippoglossus",
      illustrationPhoto: {
        src: "images/atlantic_halibut.png",
        alt: "Illustration of Atlantic Halibut.",
        title: "Illustration of Atlantic Halibut.",
      },
      Name: "Atlantic Halibut",
      index:10,
    },
  ];